config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  root 'home#top'
  resources :users
  resources :articles do
    resources :goods, only: [:create, :destroy], controller: 'articles/goods'
  end
  resources :comments, only: [:create, :destroy] do
    resources :goods, only: [:create, :destroy], controller: 'comments/goods'
  end
end

app/models/article.rb
class Article < ApplicationRecord
  validates :user_id, presence: true
  validates :title,   presence: true, length: { maximum: 50 }
  validates :content, presence: true, length: { maximum: 150 }

  belongs_to :user
  has_many :goods, dependent: :destroy, class_name: 'Articles::Good'
  has_many :comments, dependent: :destroy

  default_scope -> { order(created_at: :desc) }

  def owner?(user_id)
    self.user_id == user_id
  end
end

app/models/articles/good.rb
class Articles::Good < ApplicationRecord
  self.table_name = 'article_goods'

  validates :user_id, presence: true
  validates :article_id, presence: true

  belongs_to :user
  belongs_to :article

  counter_culture :article, column_name: 'good_count'

  def owner?(user_id)
    self.user_id == user_id
  end
end

app/controllers/articles/goods_controller.rb
class Articles::GoodsController < ApplicationController
  before_action :sign_in?, only: [:create, :destroy]

  def create
    if @article = Article.find_by(id: params[:article_id])
      @article.goods.create(user_id: current_user.id)

      # 最新のgood_countを@articleに反映させるため
      @article.reload
    end

    respond_to do |format|
      format.html { redirect_to request.referrer || root_path }
      format.js { render 'articles/goods/destroy.js.erb' }
    end
  end

  def destroy
    if @article = Article.find_by(id: params[:article_id])
      @article.goods.find_by(user_id: current_user.id)&.destroy

      # 最新のgood_countを@articleに反映させるため
      @article.reload
    end

    respond_to do |format|
      format.html { redirect_to request.referrer || root_path }
      format.js { render 'articles/goods/create.js.erb' }
    end
  end
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
  before_action :sign_in?, only: [:create, :new, :destroy, :edit, :update]
  before_action :correct_article?, only: [:destroy, :edit, :update]

  def index
    @articles = Article.includes(:user).all
  end

  def create
    @article = current_user.articles.build(article_param)
    if @article.save
      flash[:success] = '記事が投稿されました'
      redirect_to article_url(id: @article.id)
    else
      render 'new'
    end
  end

  def new
    @article = Article.new
  end

  def show
    @article = Article.includes(comments: :user).find_by(id: params[:id])
  end

  def edit
    if @article = current_user.articles.find_by(id: params[:id])
      render 'edit'
    else
      redirect_to root_path
    end
  end

  def update
    @article = current_user.articles.find_by(id: params[:id])

    if @article.update(article_param)
      flash[:success] = '記事を更新しました'
      redirect_to @article
    else
      render 'edit'
    end
  end

  def destroy
    if current_user.articles.find_by(id: params[:id]).destroy
      flash[:success] = '記事を削除しました'
    else
      flash[:danger] = '記事の削除に失敗しました'
    end
    redirect_to root_path
  end

  private

  def article_param
    params.require(:article).permit(:id, :title, :content, :user_id)
  end

  def correct_article?
    redirect_to root_path unless current_user.articles.find_by(id: params[:id])
  end
end

app/views/articles/edit.html.erb
<h1>編集</h1>

<%= form_with(model: @article, local: true) do |f| %>
  <%= render 'shared/error_messages', object: f.object %>
  <div>
    <%= f.label :title %>
    <%= f.text_field :title %>
  </div>

  <div>
    <%= f.label :content %>
    <%= f.text_field :content %>
  </div>
  <%= f.submit "更新", class: "btn" %>
<% end %>

app/views/articles/new.html.erb
<h1>投稿</h1>

<%= form_with(model: @article, url: articles_path, local: true) do |f| %>
  <%= render 'shared/error_messages', object: f.object %>

<div>
    <%= f.label :title%>
    <%= f.text_field :title%>
</div>

<div>
    <%= f.label :content%>
    <%= f.text_field :content%>
</div>

<div class="btn">
    <%= f.submit "Submit" %>
</div>

<% end %>

app/views/articles/show.html.erb
<div class="container-fluid">
  <div class="row">
    <div class="col-md-8 offset-md-2">

      <h4 class="page-title">詳細ページ</h4>
      <div class="card card-article">
        <div class="card-header card-article-header">
          <%= @article.title%>
          <%= link_to(@article.user.name, user_path(@article.user.id), {class:"link float-right"}) %>
        </div>
        <div class="card-body">
          <p class="card-text"><%= @article.content%></p>
          <p class="text-right"><%= format_time(@article.created_at) %></p>
          <%= render 'articles/goods/good_form', {article: @article} %>
          <% if user_signed_in? && @article.owner?(current_user.id) %>
            <div class="float-right">
              <%= form_with(url: edit_article_path(@article.id), method: :get, local: true) do |f| %>
                <%= f.button :type => "submit", class: "trash-button" do %>
                  <i class="fas fa-edit"></i>
                <% end %>
              <% end %>
              <%= form_with(model: @article, method: :delete, local: true) do |f| %>
                <%= f.button :type => "submit", class: "trash-button" do %>
                  <i class="fas fa-trash"></i>
                <% end %>
              <% end %>
            </div>
          <% end %>
        </div>
      </div>

      <% if @article.comments.any? %>
        <div class="comment-area">
          <h4 class="page-title">コメント</h4>
          <% @article.comments.each do |comment| %>
            <div class="element">
              <div class="card">
                <div class="card-header">
                  <%= link_to(comment.user.name, user_path(comment.user.id), {class:"link"}) %>
                </div>
                <div class="card-body">
                  <p class="card-text"><%= comment.text%></p>
                  <p class="text-right"><%= format_time(comment.created_at) %></p>

                  <%= render 'comments/goods/good_form', comment: comment %>
                  <% if user_signed_in? &&  comment.owner?(current_user.id) %>
                    <div class="float-right delete-section">
                      <%= form_with(model: comment, local: true, method: :delete) do |f| %>
                        <%= f.button :type => "submit", class: "trash-button" do %>
                          <i class="fas fa-trash"></i>
                        <% end %>
                      <% end %>
                    </div>
                  <% end %>

                </div>
              </div>
            </div>
          <% end %>
        </div>
      <% end %>

      <div class="comment-form">
        <%= form_with(model: Comment.new, url: comments_path, local: true) do |f|%>
          <%= render 'shared/error_messages', object: f.object %>
          <div class="form-group">
            <h5>コメント投稿</h5>
            <%= f.text_area :text, class:"form-control", size: "1x5"%>
          </div>
          <%= f.hidden_field :article_id, value: @article.id %>
          <%= f.hidden_field :user_id, value: current_user&.id %>
          <%= f.submit '送信', class:"btn btn-primary"%>
        <% end %>
      </div>

    </div>
  </div>
</div>