config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  root 'home#top'
  resources :users
  resources :articles do
    resources :goods, only: [:create, :destroy], controller: 'articles/goods'
  end
  resources :comments, only: [:create, :destroy] do
    resources :goods, only: [:create, :destroy], controller: 'comments/goods'
  end
end

app/models/article.rb
class Article < ApplicationRecord
  validates :user_id, presence: true
  validates :title,   presence: true, length: { maximum: 50 }
  validates :content, presence: true, length: { maximum: 150 }

  belongs_to :user
  has_many :goods, dependent: :destroy, class_name: 'Articles::Good'
  has_many :comments, dependent: :destroy

  default_scope -> { order(created_at: :desc) }

  def owner?(user_id)
    self.user_id == user_id
  end
end

app/models/articles/good.rb
class Articles::Good < ApplicationRecord
  self.table_name = 'article_goods'

  validates :user_id, presence: true
  validates :article_id, presence: true

  belongs_to :user
  belongs_to :article

  counter_culture :article, column_name: 'good_count'

  def owner?(user_id)
    self.user_id == user_id
  end
end

app/models/comments/good.rb
class Comments::Good < ApplicationRecord
  self.table_name = 'comment_goods'

  validates :user_id, presence: true
  validates :comment_id, presence: true

  belongs_to :user
  belongs_to :comment
  counter_culture :comment, column_name: 'good_count'

  def owner?(user_id)
    self.user_id == user_id
  end
end

app/controllers/articles/goods_controller.rb
class Articles::GoodsController < ApplicationController
  before_action :sign_in?, only: [:create, :destroy]

  def create
    if @article = Article.find_by(id: params[:article_id])
      @article.goods.create(user_id: current_user.id)

      # 最新のgood_countを@articleに反映させるため
      @article.reload
    end

    respond_to do |format|
      format.html { redirect_to request.referrer || root_path }
      format.js { render 'articles/goods/destroy.js.erb' }
    end
  end

  def destroy
    if @article = Article.find_by(id: params[:article_id])
      @article.goods.find_by(user_id: current_user.id)&.destroy

      # 最新のgood_countを@articleに反映させるため
      @article.reload
    end

    respond_to do |format|
      format.html { redirect_to request.referrer || root_path }
      format.js { render 'articles/goods/create.js.erb' }
    end
  end
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
  before_action :sign_in?, only: [:create, :new, :destroy, :edit, :update]
  before_action :correct_article?, only: [:destroy, :edit, :update]

  def index
    @articles = Article.includes(:user).all
  end

  def create
    @article = current_user.articles.build(article_param)
    if @article.save
      flash[:success] = '記事が投稿されました'
      redirect_to article_url(id: @article.id)
    else
      render 'new'
    end
  end

  def new
    @article = Article.new
  end

  def show
    @article = Article.includes(comments: :user).find_by(id: params[:id])
  end

  def edit
    if @article = current_user.articles.find_by(id: params[:id])
      render 'edit'
    else
      redirect_to root_path
    end
  end

  def update
    @article = current_user.articles.find_by(id: params[:id])

    if @article.update(article_param)
      flash[:success] = '記事を更新しました'
      redirect_to @article
    else
      render 'edit'
    end
  end

  def destroy
    if current_user.articles.find_by(id: params[:id]).destroy
      flash[:success] = '記事を削除しました'
    else
      flash[:danger] = '記事の削除に失敗しました'
    end
    redirect_to root_path
  end

  private

  def article_param
    params.require(:article).permit(:id, :title, :content, :user_id)
  end

  def correct_article?
    redirect_to root_path unless current_user.articles.find_by(id: params[:id])
  end
end

app/controllers/comments/goods_controller.rb
class Comments::GoodsController < ApplicationController
  before_action :sign_in?, only: [:create, :destroy]

  def create
    if @comment = Comment.find_by(id: params[:comment_id])
      @comment.goods.create(user_id: current_user.id)

      # 最新のgood_countを@commentに反映させるため
      @comment.reload
    end

    respond_to do |format|
      format.html { redirect_to request.referrer || root_path }
      format.js { render 'comments/goods/destroy.js.erb' }
    end
  end

  def destroy
    if @comment = Comment.find_by(id: params[:comment_id])
      @comment.goods.find_by(user_id: current_user.id)&.destroy

      # 最新のgood_countを@commentに反映させるため
      @comment.reload
    end

    respond_to do |format|
      format.html { redirect_to request.referrer || root_path }
      format.js { render 'comments/goods/create.js.erb' }
    end
  end
end

app/helpers/good_helper.rb
module GoodHelper
  def thumb_up?(goods)
    return false unless current_user

    goods.any? { |good| good.owner?(current_user.id) }
  end
end

app/views/articles/goods/_good.html.erb
<div id="good-<%= article.id %>">
  <%= form_with(model: article.goods.build, url: article_goods_path(article_id: article.id), remote: true) do |f| %>
      <%= f.button :type => "submit", class: "good-btn" do %>
        <i class="far fa-thumbs-up fa-fw"></i>
      <% end %>
    <%= article.good_count %>
  <% end %>
</div>

app/views/articles/goods/_good_form.html.erb
<% if thumb_up?(article.goods) %>
  <%= render 'articles/goods/ungood', {article: article} %>
<% else %>
  <%= render 'articles/goods/good', {article: article} %>
<% end %>

app/views/articles/goods/_ungood.html.erb
<div id="ungood-<%= article.id %>">
  <%= form_with(url: article_good_path(current_user.article_goods.find_by(article_id: article.id).id, article_id: article.id),
                method: :delete,
                remote: true
      ) do |f| %>
    <%= hidden_field_tag :article_id, article.id %>
    <%= f.button :type => "submit", class: "ungood-btn" do %>
      <i class="fas fa-thumbs-up fa-fw"></i>
    <% end %>
    <%= article.good_count %>
  <% end %>
</div>

app/views/articles/goods/create.js.erb
$("#good-<%= @article.id %>").html("<%= escape_javascript(render('articles/goods/good_form', article: @article)) %>");

app/views/articles/goods/destroy.js.erb
$("#good-<%= @article.id %>").html("<%= escape_javascript(render('articles/goods/good_form', article: @article)) %>");