config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  root 'home#top'
  resources :users
  resources :articles do
    resources :goods, only: [:create, :destroy], controller: 'articles/goods'
  end
  resources :comments, only: [:create, :destroy] do
    resources :goods, only: [:create, :destroy], controller: 'comments/goods'
  end
end

app/models/articles/good.rb
class Articles::Good < ApplicationRecord
  self.table_name = 'article_goods'

  validates :user_id, presence: true
  validates :article_id, presence: true

  belongs_to :user
  belongs_to :article

  counter_culture :article, column_name: 'good_count'

  def owner?(user_id)
    self.user_id == user_id
  end
end

app/models/comment.rb
class Comment < ApplicationRecord
  validates :article_id, presence: true
  validates :user_id, presence: true
  validates :text, presence: true, length: { maximum: 150 }

  belongs_to :article
  belongs_to :user
  has_many :goods, dependent: :destroy, class_name: 'Comments::Good'

  default_scope -> { order(created_at: :desc) }

  def owner?(user_id)
    self.user_id == user_id
  end
end

app/models/comments/good.rb
class Comments::Good < ApplicationRecord
  self.table_name = 'comment_goods'

  validates :user_id, presence: true
  validates :comment_id, presence: true

  belongs_to :user
  belongs_to :comment
  counter_culture :comment, column_name: 'good_count'

  def owner?(user_id)
    self.user_id == user_id
  end
end

app/controllers/articles/goods_controller.rb
class Articles::GoodsController < ApplicationController
  before_action :sign_in?, only: [:create, :destroy]

  def create
    if @article = Article.find_by(id: params[:article_id])
      @article.goods.create(user_id: current_user.id)

      # 最新のgood_countを@articleに反映させるため
      @article.reload
    end

    respond_to do |format|
      format.html { redirect_to request.referrer || root_path }
      format.js { render 'articles/goods/destroy.js.erb' }
    end
  end

  def destroy
    if @article = Article.find_by(id: params[:article_id])
      @article.goods.find_by(user_id: current_user.id)&.destroy

      # 最新のgood_countを@articleに反映させるため
      @article.reload
    end

    respond_to do |format|
      format.html { redirect_to request.referrer || root_path }
      format.js { render 'articles/goods/create.js.erb' }
    end
  end
end

app/controllers/comments/goods_controller.rb
class Comments::GoodsController < ApplicationController
  before_action :sign_in?, only: [:create, :destroy]

  def create
    if @comment = Comment.find_by(id: params[:comment_id])
      @comment.goods.create(user_id: current_user.id)

      # 最新のgood_countを@commentに反映させるため
      @comment.reload
    end

    respond_to do |format|
      format.html { redirect_to request.referrer || root_path }
      format.js { render 'comments/goods/destroy.js.erb' }
    end
  end

  def destroy
    if @comment = Comment.find_by(id: params[:comment_id])
      @comment.goods.find_by(user_id: current_user.id)&.destroy

      # 最新のgood_countを@commentに反映させるため
      @comment.reload
    end

    respond_to do |format|
      format.html { redirect_to request.referrer || root_path }
      format.js { render 'comments/goods/create.js.erb' }
    end
  end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_action :sign_in?, only: [:create, :destroy]
  before_action :correct_comment?, only: [:destroy]

  def create
    @article = Article.find_by(id: comment_params[:article_id])
    @comments = @article.comments.build(comment_params)

    flash[:success] = 'コメントが投稿されました' if @comments.save

    redirect_to request.referer || root_path
  end

  def destroy
    if current_user.comments.find_by(params[:id]).destroy
      flash[:success] = 'コメントを削除しました'
    else
      flash[:danger] = 'コメントの削除に失敗しました'
    end

    redirect_to request.referer || root_path
  end

  private

  def comment_params
    params.require(:comment).permit(:text, :article_id, :user_id)
  end

  def correct_comment?
    redirect_to root_path unless current_user.comments.find_by(id: params[:id])
  end
end

app/helpers/good_helper.rb
module GoodHelper
  def thumb_up?(goods)
    return false unless current_user

    goods.any? { |good| good.owner?(current_user.id) }
  end
end

app/views/comments/goods/_good.html.erb
<div id="good-<%= comment.id %>">
  <%= form_with(model: comment.goods.build, url: comment_goods_path(comment_id: comment.id), remote: true) do |f| %>
      <%= f.button :type => "submit", class: "good-btn" do %>
        <i class="far fa-thumbs-up fa-fw"></i>
      <% end %>
    <%= comment.good_count %>
  <% end %>
</div>

app/views/comments/goods/_good_form.html.erb
<% if thumb_up?(comment.goods) %>
  <%= render 'comments/goods/ungood', {comment: comment} %>
<% else %>
  <%= render 'comments/goods/good', {comment: comment} %>
<% end %>

app/views/comments/goods/_ungood.html.erb
<div id="ungood-<%= comment.id %>">
  <%= form_with(url: comment_good_path(comment_id: comment.id, id: current_user.comment_goods.find_by(comment_id: comment.id).id),
                method: :delete,
                remote: true
      ) do |f| %>
    <%= hidden_field_tag :comment_id, comment.id %>
    <%= f.button :type => "submit", class: "ungood-btn" do %>
      <i class="fas fa-thumbs-up fa-fw"></i>
    <% end %>
    <%= comment.good_count %>
  <% end %>
</div>

app/views/comments/goods/create.js.erb
$("#good-<%= @comment.id %>").html("<%= escape_javascript(render('comments/goods/good_form', comment: @comment)) %>");

app/views/comments/goods/destroy.js.erb
$("#good-<%= @comment.id %>").html("<%= escape_javascript(render('comments/goods/good_form', comment: @comment)) %>");