config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  root 'home#top'
  resources :users
  resources :articles do
    resources :goods, only: [:create, :destroy], controller: 'articles/goods'
  end
  resources :comments, only: [:create, :destroy] do
    resources :goods, only: [:create, :destroy], controller: 'comments/goods'
  end
end

app/views/layouts/_header.html.erb
<div class="header">
  <nav class="navbar navbar-light bg-dark">

    <%= link_to root_path, {class: "link"} do %>
      <%= image_tag 'icon.png', class: "d-inline-block header-icon"%>
      <span class="header-title">  *Blog app</span>
    <% end %>
    <div class="float-right">
      <span class="post-link"><%= link_to "投稿する", new_article_path, { class:"link" } %></span>
      <% if user_signed_in?%>
        <span class="text-light user-name link">
          <%= link_to current_user.name, user_path(current_user.id), {class:"link"} %>
        </span>
        <div class="btn btn-info sm">
          <%=link_to "ログアウト", destroy_user_session_path, method: :delete, class: "header-logout-button" %>
        </div>
      <% else %>
        <div class="btn btn-success btn-sm">
         <%=link_to "ログイン", new_user_session_path, class: "header-login-button" %>
        </div>
        <div class="btn btn-info btn-sm">
          <%=link_to "新規登録", new_user_registration_path, class: "header-signup-button" %>
        </div>
      <% end %>
    </div>
  </nav>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Blog</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>

    <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js" integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/js/bootstrap.min.js" integrity="sha384-OgVRvuATP1z7JjHLkuOU7Xw704+h835Lr+6QL9UvYjZE3Ipu6Tp75j7Bh/kR0JKI" crossorigin="anonymous"></script>
    <link href="https://use.fontawesome.com/releases/v5.6.1/css/all.css" rel="stylesheet">
  </head>

  <body class="page-color">
  <%= render 'layouts/header' %>

  <% flash.each do |type, message| %>
    <div class="alert alert-<%= type %>"><%= message %></div>
  <% end %>

  <%= yield %>
  </body>
</html>